const ADD_QUERY = 'ADD_QUERY';
const GET_QUERIES = 'GET_QUERIES';
const GET_QUERY_INFO = 'GET_QUERY_INFO';
const SET_QUERY_ERRORS = 'SET_QUERY_ERRORS';

export { ADD_QUERY, GET_QUERIES, GET_QUERY_INFO, SET_QUERY_ERRORS };
