const ADD_CHART = 'ADD_CHART';
const ADD_DASHBOARD = 'ADD_DASHBOARD';
const GET_DASHBOARD = 'GET_DASHBOARD';
const GET_DASHBOARDS = 'GET_DASHBOARDS';
const SET_DASHBOARD_ERRORS = 'SET_DASHBOARD_ERRORS';

export { ADD_CHART, ADD_DASHBOARD, GET_DASHBOARD, GET_DASHBOARDS, SET_DASHBOARD_ERRORS };
