const ADD_DASHBOARD = 'ADD_DASHBOARD';
const GET_DASHBOARD = 'GET_DASHBOARD';
const GET_DASHBOARD_PARAMS = 'GET_DASHBOARD_PARAMS';
const SET_DASHBOARD_ERRORS = 'SET_DASHBOARD_ERRORS';
const UPDATE_DASHBOARD_PARAM = 'UPDATE_DASHBOARD_PARAM';

export {
  ADD_DASHBOARD,
  GET_DASHBOARD,
  GET_DASHBOARD_PARAMS,
  SET_DASHBOARD_ERRORS,
  UPDATE_DASHBOARD_PARAM,
};
