const ADD_CHART = 'ADD_CHART';
const DELETE_CHART = 'DELETE_CHART';
const GET_CHARTS = 'GET_CHARTS';
const SET_CHART_ERRORS = 'SET_CHART_ERRORS';
const UPDATE_CHART = 'UPDATE_CHART';

export { ADD_CHART, DELETE_CHART, GET_CHARTS, SET_CHART_ERRORS, UPDATE_CHART };
